tap "homebrew/autoupdate"
tap "homebrew/cask-fonts"
tap "ferdium/ferdium"

cask "alfred"
cask "amethyst"
cask "bettertouchtool"
cask "docker"
cask "google-chrome"
cask "pgadmin4"
cask "visual-studio-code"
cask "zoom"

brew "zsh"
brew "ferdium-nightly"
