tap "homebrew/autoupdate"
tap "homebrew/cask-fonts"

cask "alfred"
cask "amethyst"
cask "bettertouchtool"
cask "docker"
cask "ferdium"
cask "google-chrome"
cask "pgadmin4"
cask "visual-studio-code"
cask "zoom"

brew "htop"
brew "zsh"
